### ISSUE TITLE
Cookie max-age/expires

### ISSUE THREAD

**Issue by hey-red** [aspnet/Session#141] opened 2016-12-10 12:29 UTC
How about making this an option?

**Comment by Tratcher** [comment] 2016-12-10 15:02
Duplicate of https://github.com/aspnet/Session/issues/132.
Session lifetime is controlled primarily by the cache, not by the cookie.
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionOptions.cs#L48

**Closed by Tratcher** 2016-12-10 15:02 UTC
Labels: duplicate
