### ISSUE TITLE
Error closing the session

### ISSUE THREAD

**Issue by 1amirjalai** [aspnet/Session#192] opened 2017-09-23 17:47 UTC
After migrating to version 2.0 now i have this error " **Error closing the session**. " every second

is there anything i can do? 
```
SourceContext
Microsoft.AspNetCore.Session.SessionMiddleware

System.OperationCanceledException: The operation was canceled.

   at System.Threading.CancellationToken.ThrowOperationCanceledException()

   at Microsoft.AspNetCore.Session.DistributedSession.<CommitAsync>d__32.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
```

**Comment by Tratcher** [comment] 2017-09-23 17:51
Duplicate of https://github.com/aspnet/Session/issues/189

**Closed by Tratcher** 2017-09-23 17:51 UTC
Labels: duplicate
